### ISSUE TITLE
Doesn't seem to work with ip netns exec

### ISSUE THREAD

**Issue by tzugen** [rd235/cado#7]
Hello :)

I am trying to allow users to launch a process into a different network namespace without using sudo.
I added the net_admin capability, but still ``ip`` complains:

     setting the network namespace "ns" failed: Operation not permitted

Any ideas what might be wrong?

**Comment by rd235** [comment]
I think CAP_SYS_ADMIN is required to create namespaces.

from capabilities(7):
> CAP_SYS_ADMIN:...
>  employ  CLONE_* flags that create new namespaces with clone(2)
>  and unshare(2) (but, since Linux 3.8, creating user namespaces
>  does not require any capability);

The command:
ip netns add testns
uses unshare(CLONE_NEWNET) to create the namespace.

You can create user namespaces (see for example vdens: https://github.com/rd235/vdens )
